stages:
  data_ingestion:
    cmd: python src/extraction.py
    deps:
      - src/extraction.py
    outs:
      - data/raw/flood_raw.csv
  Preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
    outs:
      - data/transform
  Training:
    cmd: python src/train.py
    deps:
      - src/train.py
    metrics:
      - artifacts/scores.json:
          cache: false
  Best_model:
    cmd: python src/best_model.py
    deps:
      - src/best_model.py
    outs:
      - artifacts/best_model
      - artifacts/best_model_info.json

  
